<script setup lang="ts">
///////////////////////////////////////////////////////////////////////////
//
// This is a very simple example. See TodoList2/ListItem.vue for more on emits.
// Usage:
//
//   <EmitsDemo
//     @handle-mounted="(message) => console.log(message)"
//     :on-mount="(message) => console.log(message)"
//   />
//
// Here the @handle-mounted is optional, but on-mount is requird.
// Generally, emitting events is considered the more idiomatic approach.
// However, if you really need to enforce that a function be passed down,
// then using a prop and making it required is a valid approach. TL;DR:
// use props when you need a strict contract.
//
///////////////////////////////////////////////////////////////////////////

import { onMounted } from 'vue'

export type Props = {
  ///////////////////////////////////////////////////////////////////////////
  //
  // ⚠️ If you name the callback onHandleMounted
  //
  //   export type Props = {
  //     onHandleMounted: (message: string) => void
  //   }
  //
  // Then you pass an emit as follows:
  //
  //   @handle-mounted="(message) => console.log(message)"
  //
  // Then TypeScript will not complain. Why?
  //
  // Inline event listeners in templates are treated as props by TypeScript’s JSX/TSX inference layer
  // — even though Vue itself does NOT treat them as props. Essentially, TypeScript thinks
  // @handle-mounted is a prop. Basically, the following type definition that is generated by Vue
  // is something like this:
  //
  //  onHandleMounted: (message: string) => void
  //  "onHandle-mounted"?: ((message: string) => any)
  //
  // But when we write:
  //
  //    <EmitsDemo @handle-mounted="(message) => console.log(message)" />
  //
  // TS interprets this as:  { "onHandle-mounted": (message: string) => void }
  //
  // And since "onHandle-mounted" is considered a valid alternative key for your required
  // prop, TypeScript thinks: “Yep, the required prop is present.”
  // Even though Vue does not treat this as a prop at runtime.
  //
  // This is one of Vue’s strangest TypeScript edge‑cases. The real takeaway here is don't name
  // your emits and callback props too similarly, otherwise you'll hit this weird edge case.
  //
  // More generally, this is also a good rule to folloe:
  // Avoid onX names to prevent template/TS inference collisions
  //
  ///////////////////////////////////////////////////////////////////////////

  onMount: (message: string) => void
}
export type Emits = {
  (e: 'handle-mounted', message: string): void
}

const { onMount } = defineProps<Props>()

// Note: Vue’s emits are optional by design.
// This means you can't make an emit “required” at the template level.
// If the goal is “the parent MUST provide a handler,” then emits cannot
// enforce that, but a callback prop can.
const emit = defineEmits<Emits>()

onMounted(() => {
  setTimeout(() => {
    // In retrospect, it probably makes more sense to call
    // the event 'mounted', and call the callback prop handleMounted.
    emit('handle-mounted', `A 'handle-mounted' event was emitted, and the listener ran!`)
    onMount('The on-mount callback prop ran!')
  }, 3000)
})
</script>

<!-- ======================================================================
 
======================================================================= -->

<template>
  <div
    class="bg-primary mx-auto flex size-50 items-center justify-center rounded-2xl border border-[rgba(0,0,0,0.35)] font-mono text-white shadow"
  >
    EmitsDemo.vue
  </div>
</template>
